# ------------------- PATHS -------------------
paths:
  dev_root:        data/dcase2025t2/dev_data/raw            # 7-machine “development” set
  eval_root:       data/dcase2025t2/eval_data/raw           # 8-machine “additional train + eval test” set
  pretrained_dir:  pretrained                                # where pre-train model is saved
  out_root:        outputs/task2/MeghanKret_Cooper_task2_1   # CSVs & later submission.zip
  dev_results:     outputs/task2/dev_results
# ------------------- AUDIO FEATS -------------
audio:
  sample_rate: 16000
  n_fft:       1024
  hop_length:  512
  n_mels:      128
  context:     5        # frames concatenated → 128×5 = 640-D

# ------------------- MODEL -------------------
model:
  hidden:     128       # width of every hidden FC layer
  bottleneck: 8         # latent dim

# ------------------- TRAINING ----------------
train:
  batch_size:        256
  lr:                0.001
  epochs_pretrain:   5      # dev pre-train epochs
  epochs_finetune:   20     # per-machine fine-tune epochs
  gamma_percentile:  0.90

# ------------------- MISC --------------------
device: auto          # "cpu", "cuda", "mps", or "auto"
